- name: List files on remote server
  hosts: webservers
  remote_user: ec2-user

  vars_prompt:
    - name: trello_key
      prompt: What is your Trello API Key?
      private: yes
    - name: trello_token
      prompt: What is your Trello API Token?
      private: yes

  tasks:
    - name: Install Git but do not update each time
      ansible.builtin.yum:
        name: git
        state: installed
      become: yes
    - name: Install Python 3.0
      ansible.builtin.yum:
        name: python3
        state: latest
      become: yes
    - name: Install Poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | python3 -
        creates: ./log.txt
    - name: Create To-Do app directory
      ansible.builtin.file:
        path: /opt/todoapp
        state: directory
        owner: ec2-user
      become: yes
    - name: Create and populate /opt/todoapp using Git
      ansible.builtin.git:
        repo: 'https://github.com/The-Build-Master/DevOps-Course-Starter.git'
        version: 'Module-4'
        dest: /opt/todoapp
        clone: yes
        update: yes
    - name: Set up project dependencies
      ansible.builtin.command:
        chdir: /opt/todoapp
        cmd: /home/ec2-user/.local/bin/poetry install
    - name: Create .env file
      ansible.builtin.template:
        src: /home/ec2-user/.env.j2
        dest: /opt/todoapp/.env  
    - name: Copy todoapp.service file to new location
      ansible.builtin.copy:
        src: /opt/todoapp/ansible/todoapp.service
        dest: /etc/systemd/system/todoapp.service
      become: yes
   - name: Add systmd task to start up To-Do app 
      ansible.builtin.systemd:
        name: todoapp.service
        daemon_reload: yes
        state: restarted
      become: yes        