name: Continuous Integration 
on: 
  push:
    paths-ignore:
      - 'README.*'
      - 'documentation/**'
      - 'ansible/**'

  pull_request:
    paths-ignore:
      - 'README.*'
      - 'documentation/**'
      - 'ansible/**'

jobs: 
  build: 
    name: Build and test 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - run: docker build --target test --tag my-test-image .
      - run: docker run --env-file .env.test my-test-image

  job-two:
    name: Publish
    needs: build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps: 
      # set username and password as secret values in github repository?
        - run: echo {{ github.ref}}
        - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_USERPWD }}
        - run: echo Publishing!
